### ISSUE TITLE
Date calculator seems to not working properly

### ISSUE THREAD

**Issue by rs1-es** [Myzel394/NumberHub#26]
![Screenshot_20240723-182754](https://github.com/user-attachments/assets/ed110d3c-4608-4495-af4a-f1077f248d9f)

'Años' means Years in spanish. It should show 33.0 or something like that, not 33.48 years (33 years and almost 6 months). I think the same thing happens with the Months tab.

Thanks for your work maintaining this app.

**Comment by crisp5** [comment]
This happens because it's using 360-day years [here](https://github.com/Myzel394/NumberHub/blob/master/feature/datecalculator/src/main/java/app/myzel394/numberhub/feature/datecalculator/difference/ZonedDateTimeDifference.kt#L115) (common in financial/accounting circles) instead of the more general 365-day year. I feel like the 365-day convention makes more sense here though, unless I'm missing something.
